image: fedora

build:
  stage: build
  before_script:
    - dnf install -q -y cmake make gcc qt5-qtbase-devel qt5-qtcharts-devel
  script:
    - cmake src
    - make
  artifacts:
    paths:
      - obc_gui
  
package:
  stage: deploy
  before_script:
    - dnf install -q -y rpm-build
  script:
    - mkdir -p $HOME/rpmbuild/SPECS
    - cp package/obc_gui.spec $HOME/rpmbuild/SPECS/obc_gui.spec
    - rpmbuild -bb $HOME/rpmbuild/SPECS/obc_gui.spec
    - cp $HOME/rpmbuild/RPMS/x86_64/* package/
  artifacts:
    paths:
      - package/*.rpm

deploy:
    stage: deploy
    when: manual
    needs: [package]
    dependencies:
        - package
    before_script:
        - mkdir -p ~/.ssh
        - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - dnf install -q -y openssh openssh-clients
    script:
        - scp package/*.rpm deployuser@rpm.sdsurocketproject.org:/opt/rpm-repo/
        - ssh deployuser@rpm.sdsurocketproject.org "createrepo --update /opt/rpm-repo"
