image: fedora

build:
  stage: build
  before_script:
    - dnf install -q -y cmake make gcc qt5-qtbase-devel qt5-qtcharts-devel
  script:
    - cmake src
    - make
  artifacts:
    paths:
      - obc_gui
  
package:
  stage: deploy
  before_script:
    - dnf install -q -y rpm-build
  script:
    - mkdir -p $HOME/rpmbuild/SPECS
    - cp package/obc_gui.spec $HOME/rpmbuild/SPECS/obc_gui.spec
    - rpmbuild -bb $HOME/rpmbuild/SPECS/obc_gui.spec
    - cp $HOME/rpmbuild/RPMS/x86_64/* package/
  artifacts:
    paths:
      - package/*.rpm
